version: '3.8'

services:
    nginx:
        image: nginx:1.21.1
        ports: 
            - 80:80
        volumes:
            - ./www:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php-fpm

    php-fpm:
        build: ./.docker/php
        working_dir: /var/www
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./www:/var/www
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
        volumes:
            - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 10

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
        depends_on:
            mysql:
                condition: service_healthy

volumes:
    mysqldata: